# Generated by Django 3.1.6 on 2021-02-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('report_path', models.FilePathField()),
            ],
        ),
    ]
