# Generated by Django 3.1.6 on 2021-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocreate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=250)),
                ('report', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
