# Generated by Django 3.1.6 on 2021-02-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocreate', '0002_auto_20210204_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyINN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/%Y/%m/%d')),
                ('inn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocreate.companyinn')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
