# Generated by Django 3.1.6 on 2021-02-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocreate', '0003_auto_20210204_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreport',
            name='inn',
        ),
    ]
