# Generated by Django 3.1.6 on 2021-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocreate', '0004_remove_companyreport_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('report_path', models.FilePathField(path='/media/')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyINN',
        ),
        migrations.DeleteModel(
            name='CompanyReport',
        ),
    ]
